const statusEl = document.getElementById("status");
const reportBtn = document.getElementById("report");
const errorEl = document.getElementById("error");
const errorCodeEl = document.getElementById("error-code");
const errorMsgEl = document.getElementById("error-msg");
const reportErrorBtn = document.getElementById("report-error");
const button = document.getElementById("fill");

// The most recent failure, { code, detail, tabUrl }, so "Report a problem"
// can pre-fill its diagnostics. Null when the last run didn't fail.
let lastError = null;

// crosswordlabs.com, with or without www, over http or https.
const SITE_RE = /^https?:\/\/(www\.)?crosswordlabs\.com\//i;
// Pages that hold a single puzzle. A missing grid anywhere else (the home
// page, search results) is expected, so it isn't offered as a bug report.
const PUZZLE_PATH_RE = /^\/(view|embed)\//i;
const ISSUES_URL = "https://github.com/Trogiken/crossword-labs-autofill/issues/new";
// Keeps the pre-filled issue URL well under GitHub's length limit.
const MAX_DETAIL = 1500;

// Error codes shown to the user and put in bug reports. Keep them stable so
// old reports stay searchable; add new ones rather than renumbering.
//   E1xx  the page doesn't look like a puzzle the extension understands
//   E2xx  the puzzle was found but filling or saving it failed
//   E3xx  the extension couldn't run in the tab at all
//   E9xx  unexpected exception
const ERRORS = {
  E101: "No puzzle grid found on this page.",
  E201: "Found the puzzle but couldn't fill any boxes.",
  E202: "Filled the boxes but couldn't save progress, so the site won't grade it.",
  E301: "Couldn't run on this page.",
  E302: "No response from the page.",
  E901: "Something unexpected went wrong."
};

function errorText(e) {
  return String((e && (e.stack || e.message)) || e);
}

function setStatus(text, kind) {
  statusEl.textContent = text;
  statusEl.className = kind || "";
  statusEl.hidden = false;
}

// URL of a pre-filled GitHub issue, for the given failure or a general
// report when err is null. Nothing is sent anywhere unless the user reviews
// and submits the issue.
function issueUrl(err, tabUrl) {
  const code = err ? err.code : "none";
  const body = [
    "**What happened**",
    "<!-- Anything you can add helps: what you clicked, what you saw. -->",
    "",
    "",
    "**Diagnostics** (generated by the extension)",
    "",
    "```",
    `Code:      ${code}`,
    `Message:   ${err ? ERRORS[code] : "-"}`,
    `Detail:    ${((err && err.detail) || "-").slice(0, MAX_DETAIL)}`,
    `Page:      ${tabUrl || "-"}`,
    `Extension: ${chrome.runtime.getManifest().version}`,
    `Browser:   ${navigator.userAgent}`,
    "```"
  ].join("\n");
  const url = new URL(ISSUES_URL);
  url.searchParams.set("title", err ? `[${code}] ${ERRORS[code]}` : "Problem report");
  url.searchParams.set("body", body);
  return url.toString();
}

// Runs inside the page's own JS context (world: "MAIN") so it can read the
// page's globals. This function is serialized and injected, so it must be
// self-contained: no references to anything outside its own body.
//
// Every step has a fallback so a small change to the site doesn't break it:
//   - word starts come from index_to_row_column/index_to_direction, or are
//     rebuilt from each grid cell's own across/down metadata;
//   - CROSSWORD_ID comes from the global, or from the page's og:image URL;
//   - the page is only reloaded if progress was actually saved.
//
// Returns { ok: true, msg } or { ok: false, code, detail }.
function pageFill() {
  try {
    return fill();
  } catch (e) {
    return { ok: false, code: "E901", detail: String((e && e.stack) || e) };
  }

  function fill() {
    // typeof is safe on undeclared names; each global is read once, here.
    const pageGrid = typeof grid !== "undefined" ? grid : undefined;
    const rowCol = typeof index_to_row_column !== "undefined" ? index_to_row_column : undefined;
    const dirs = typeof index_to_direction !== "undefined" ? index_to_direction : undefined;
    let id = typeof CROSSWORD_ID !== "undefined" ? CROSSWORD_ID : undefined;

    if (!Array.isArray(pageGrid) || !pageGrid.length) {
      return { ok: false, code: "E101", detail: `grid is ${Array.isArray(pageGrid) ? "empty" : typeof pageGrid}` };
    }

    // The solution letter at (r, c), or null for a black square / off the grid.
    const charAt = (r, c) => {
      const cell = pageGrid[r] && pageGrid[r][c];
      return cell && typeof cell.char === "string" && cell.char ? cell.char : null;
    };

    // 1. Write each letter into the on-screen grid (visual only).
    let filled = 0;
    for (let r = 0; r < pageGrid.length; r++) {
      const row = pageGrid[r] || [];
      for (let c = 0; c < row.length; c++) {
        const ch = charAt(r, c);
        if (!ch) continue;
        const t = document.querySelector(`#cx-${r}-${c} .cx-a`);
        if (t) { t.textContent = ch.toUpperCase(); filled++; }
      }
    }

    // 2. Work out where each word starts: index -> { row, col, across }.
    const starts = {};
    if (rowCol && dirs && typeof dirs === "object") {
      for (const idx in dirs) {
        const rc = rowCol[idx];
        if (rc && Number.isInteger(rc.row) && Number.isInteger(rc.col)) {
          starts[idx] = { row: rc.row, col: rc.col, across: dirs[idx] === "across" };
        }
      }
    }
    if (!Object.keys(starts).length) {
      for (let r = 0; r < pageGrid.length; r++) {
        const row = pageGrid[r] || [];
        for (let c = 0; c < row.length; c++) {
          const cell = row[c];
          if (!cell) continue;
          // Same order as the site's own table: "down" wins if both share an index.
          for (const dir of ["across", "down"]) {
            const w = cell[dir];
            if (w && w.is_start_of_word && w.index != null) {
              starts[w.index] = { row: r, col: c, across: dir === "across" };
            }
          }
        }
      }
    }

    // 3. Find the puzzle ID the site uses for its localStorage keys.
    if (id == null || id === "") {
      const og = document.querySelector('meta[property="og:image"]');
      const m = og && /\/image\/([^/.]+)\.svg/.exec(og.content || "");
      if (m) id = m[1];
    }
    const hasId = id != null && id !== "";

    // 4. Save every word the same way the site does when you type it.
    let saved = 0;
    let storageError = "";
    if (hasId) {
      for (const idx in starts) {
        let { row, col, across } = starts[idx];
        let word = "";
        let ch;
        while ((ch = charAt(row, col))) {
          word += ch;
          across ? col++ : row++;
        }
        if (!word) continue;
        try {
          localStorage.setItem(`${id}-${idx}`, word);
          saved++;
        } catch (e) {
          storageError = (e && e.name) || String(e);
        }
      }
    }

    if (saved) {
      // Give the popup a moment to receive the result before the page goes away.
      setTimeout(() => location.reload(), 100);
      return { ok: true, msg: `Filled ${saved} words. Reloading to grade…` };
    }

    const detail = [
      `rows=${pageGrid.length}`,
      `filled=${filled}`,
      `cells=${document.querySelectorAll(".cx-a").length}`,
      `starts=${Object.keys(starts).length}`,
      `tables=${rowCol && dirs ? "yes" : "no"}`,
      `id=${hasId ? "yes" : "no"}`,
      storageError && `storage=${storageError}`
    ].filter(Boolean).join(" ");
    return { ok: false, code: filled ? "E202" : "E201", detail };
  }
}

// Checks the tab, injects pageFill, and normalizes every outcome to
// { ok: true, msg } | { ok: false, code, detail } | { ok: false, msg }.
// The last form is for user mistakes, which don't show the error panel.
async function run(tab) {
  const tabUrl = (tab && tab.url) || "";
  if (!tab || !SITE_RE.test(tabUrl)) {
    return { ok: false, msg: "Open a Crossword Labs puzzle first." };
  }

  let res;
  try {
    [res] = await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      world: "MAIN",
      func: pageFill
    });
  } catch (e) {
    return { ok: false, code: "E301", detail: errorText(e) };
  }

  const out = res && res.result;
  if (!out) return { ok: false, code: "E302", detail: "" };
  if (out.ok) return out;
  if (out.code === "E101" && !PUZZLE_PATH_RE.test(new URL(tabUrl).pathname)) {
    return { ok: false, msg: "Open a Crossword Labs puzzle first." };
  }
  return { ok: false, code: ERRORS[out.code] ? out.code : "E901", detail: out.detail };
}

button.addEventListener("click", async () => {
  button.disabled = true;
  lastError = null;
  errorEl.hidden = true;
  setStatus("Filling…");

  let tab;
  let out;
  try {
    [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    out = await run(tab);
  } catch (e) {
    out = { ok: false, code: "E901", detail: errorText(e) };
  }

  if (out.ok) {
    // Leave the button disabled; the page is about to reload.
    setStatus(out.msg, "ok");
    return;
  }
  if (out.code) {
    statusEl.hidden = true; // the error panel takes its place
    lastError = { code: out.code, detail: out.detail, tabUrl: tab && tab.url };
    errorCodeEl.textContent = out.code;
    errorMsgEl.textContent = ERRORS[out.code];
    errorEl.hidden = false;
    reportErrorBtn.focus();
  } else {
    setStatus(out.msg, "err");
  }
  button.disabled = false;
});

// Both buttons open the same issue: pre-filled with the last error if there
// is one, otherwise a general report.
async function openReport() {
  let tabUrl = lastError ? lastError.tabUrl : "";
  if (!lastError) {
    // Only name the page if it's a Crossword Labs page; the issue is public.
    try {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (tab && SITE_RE.test(tab.url || "")) tabUrl = tab.url;
    } catch (e) { }
  }
  chrome.tabs.create({ url: issueUrl(lastError, tabUrl) });
}
reportBtn.addEventListener("click", openReport);
reportErrorBtn.addEventListener("click", openReport);

// Open links in a new tab (plain links don't navigate from a popup reliably).
for (const a of document.querySelectorAll("a")) {
  a.addEventListener("click", (e) => {
    e.preventDefault();
    if (a.href) chrome.tabs.create({ url: a.href });
  });
}
